# version: '3'
services:
  penguin-classifier:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/penguins_model.pkl
    restart: unless-stopped